### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by mattgodbolt** [michael-golfi/monaco-editor#1]
Hi: thanks for setting this up.  Any chance you can mirror the release tags too? That way I can specify a particular version instead of whatever '*' gives me.

**Comment by michael-golfi** [comment]
Alright I pushed all of the tags. This reflects v0.7.0 if I'm not mistaken (I didn't originally think that anyone would use this as I only needed it for a small project).

**Comment by michael-golfi** [comment]
I just realized they didn't publish tags for [v0.7.0](https://github.com/Microsoft/monaco-editor/commit/9ff02988e64369aeffcfe30a60e52ffc6906aa56). I just did that now.

**Comment by mattgodbolt** [comment]
Thanks so much! Seems a long shot, but do you happen to have any ideas on Microsoft/monaco-editor#18? That's now the only thing preventing me from moving forward and using Monaco in a public project.

**Comment by michael-golfi** [comment]
I might be able to help. I'll need to change the way they compile the typescript. I'll give that a shot tonight.

**Comment by mattgodbolt** [comment]
That would be great! I found a workaorund that involves having two bundles;
one for Monaco etc and one for the rest of my site, so it's not so
important: but thanks!

**Comment by mattgodbolt** [comment]
MS have just pushed 0.8.0 - any chance you could update to pick that up? Thanks again!
